# Site settings
title: International Underground
email: greg@harmsboone.org
description: Unseen, unheard, uncovered
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://internationalunderground.org" # the base hostname & protocol for your site
twitter_username: Intl_undergrnd
github_username:  Intl_undergrnd
featured_series: the-spirit-of-entrepreneurs
# Build settings
markdown: kramdown
permalink: /:year/:title/
gems:
  - jekyll-archives

# archives
jekyll-archives:
  enabled: 
    - year
    - month
  layout: category_index
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'


#defaults
defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
    scope:
      collection: series
    values:
      layout: series
exclude:
- ".ruby-version"
# Collections
collections:
  series:
    permalink: /series/:title/
    output: true

full_rebuild: true